import { IComplaintApi } from '@modal/complaint-form.modal'
import { IEnquiryApi } from '@modal/Enquiry-form.modal'
import { ILocationApi } from '@modal/location-building-room.modal'
import { IRoomsApi } from '@modal/rooms.modal'
import { IUserCreationFormApi } from '@modal/user-creation.modal'

export const locationApiDefaultData: ILocationApi = {
  buildings: [
    {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      longitude: '',
      publish: true,
      rooms: [
        {
          createAt: '',
          createdBy: '',
          deleted: false,
          id: 0,
          publish: true,
          roomCapacity: 0,
          roomFloor: 0,
          roomName: '',
          roomType: '',
          updateAt: '',
          updatedBy: '',
        },
      ],
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
  ],
  createAt: '',
  createdBy: '',
  deleted: false,
  id: 0,
  locationName: '',
  publish: true,
  updateAt: '',
  updatedBy: '',
}

export const userCreationApiDefaultData: IUserCreationFormApi = {
  address: '',
  buildingsDTO: [
    {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      locationsDTO: {
        createAt: '',
        createdBy: '',
        deleted: false,
        id: 0,
        locationName: '',
        publish: true,
        updateAt: '',
        updatedBy: '',
      },
      longitude: '',
      publish: true,
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
  ],
  email: '',
  id: 0,
  name: '',
  password: '',
  phoneNumber: '',
  roomsDTO: {
    buildingsDTO: {
      buildingAddress: '',
      buildingName: '',
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      latitude: '',
      locationsDTO: {
        createAt: '',
        createdBy: '',
        deleted: false,
        id: 0,
        locationName: '',
        publish: true,
        updateAt: '',
        updatedBy: '',
      },
      longitude: '',
      publish: true,
      updateAt: '',
      updatedBy: '',
      zipCode: '',
    },
    id: 0,
    roomCapacity: 0,
    roomFloor: 0,
    roomName: '',
    roomType: '',
  },
  userType: '',
  zipCode: '',
}

export const roomCreationApiDafaultData: IRoomsApi = {
  buildingsDTO: {
    buildingAddress: '',
    buildingName: '',
    createAt: '',
    createdBy: '',
    deleted: false,
    id: 0,
    latitude: '',
    locationsDTO: {
      createAt: '',
      createdBy: '',
      deleted: false,
      id: 0,
      locationName: '',
      publish: true,
      updateAt: '',
      updatedBy: '',
    },
    longitude: '',
    publish: true,
    updateAt: '',
    updatedBy: '',
    zipCode: '',
  },
  id: 0,
  roomCapacity: 0,
  roomFloor: 0,
  roomName: '',
  roomType: '',
}

export const enquiryFormApiDeaultData: IEnquiryApi = {
  address: '',
  adminId: 0,
  buildings: 0,
  description: '',
  duration: '',
  email: '',
  enquiryStatus: '',
  id: 0,
  locations: 0,
  name: '',
  numberOfPeople: 0,
  phoneNumber: '',
  referral: '',
  roomChoice: '',
  zipCode: '',
}

export const complaintFormApiDeaultData: IComplaintApi = {
  attachment: '',
  complaintDescription: '',
  compaintStatus: '',
  complaintsType: '',
  contactNumber: '',
  downloadPath: '',
  id: 0,
  user: 0,
}
